name: CD - Update Deployment Repo

on:
  workflow_run:
    workflows: ["CI - Build and Push Image"]
    types:
      - completed

jobs:
  update-deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: <github-username>/k8s-deployment-repo
          token: ${{ secrets.GH_PAT }}
          path: deployment

      - name: Update Image Tag
        run: |
          cd deployment

          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.event.workflow_run.head_sha }}|g" deployment.yaml

      - name: Commit Changes
        run: |
          cd deployment
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag"
          git push